# Generated by Django 4.2.9 on 2024-04-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
