# Generated by Django 4.2.9 on 2024-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0017_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
